spring.application.name=portfolio-service
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=paper_trading
spring.datasource.password=paper123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.batch.jdbc.initialize-schema=always